accepted = [
    "Apache-2.0",
    "0BSD",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "Zlib",
    "ISC",

    "MPL-2.0"
]
ignore-build-dependencies = false
ignore-dev-dependencies = false
